all:
    vars:
        openhpc_cluster_name: ms
        cluster_domain_suffix: in.nvs.bmrc.ox.ac.uk
        cluster_home_volume: false
        cluster_compute_groups: ["a100","general","general-100disk","legacy","ood","v100","v100-full"]

control:
    hosts:
        ms-control:
            ansible_host: 10.56.2.244
            instance_id: 35504767-0d91-4580-b54f-8b7d7f4a5840
            networks: {"analytics-vxlan":{"fixed_ip_v4":"10.56.2.244","fixed_ip_v6":""}}
            node_fqdn: ms-control.in.nvs.bmrc.ox.ac.uk
    vars:
        appliances_state_dir: /var/lib/state # NB needs to be set on group not host otherwise it is ignored in packer build!

# --- login nodes ---
ms_interactive:
    hosts:
        ms-login-00:
            ansible_host: 10.56.2.112
            instance_id: 38b8f600-bd56-473c-8c53-19515d57ef92
            image_id: bfaefe6c-8eac-447b-8c58-4fd05c2e1161
            networks: {"analytics-vxlan":{"fixed_ip_v4":"10.56.2.112","fixed_ip_v6":""}}
            node_fqdn: ms-login-00.in.nvs.bmrc.ox.ac.uk
            node_fip: 10.167.2.160

interactive:
    children:
        ms_interactive:


login:
    children:
        ms_interactive:

# --- compute nodes ---
ms_a100:
    hosts:
        ms-a100-00:
            ansible_host: 10.56.0.35
            instance_id: 701a2f61-ca57-4746-bfd6-947b46769324
            networks: {"analytics-vxlan":{"fixed_ip_v4":"10.56.0.35","fixed_ip_v6":""}}
            node_fqdn: ms-a100-00.in.nvs.bmrc.ox.ac.uk
        ms-a100-01:
            ansible_host: 10.56.1.225
            instance_id: 60c95431-6ecd-41aa-a11c-45bfed9e5d47
            networks: {"analytics-vxlan":{"fixed_ip_v4":"10.56.1.225","fixed_ip_v6":""}}
            node_fqdn: ms-a100-01.in.nvs.bmrc.ox.ac.uk
        ms-a100-02:
            ansible_host: 10.56.1.73
            instance_id: 003ad207-24ab-4eb7-a7a9-e6a83e205096
            networks: {"analytics-vxlan":{"fixed_ip_v4":"10.56.1.73","fixed_ip_v6":""}}
            node_fqdn: ms-a100-02.in.nvs.bmrc.ox.ac.uk
        ms-a100-03:
            ansible_host: 10.56.1.90
            instance_id: 5e6ed5fb-1d92-4d4c-8c46-fe7b76f996e6
            networks: {"analytics-vxlan":{"fixed_ip_v4":"10.56.1.90","fixed_ip_v6":""}}
            node_fqdn: ms-a100-03.in.nvs.bmrc.ox.ac.uk
    vars:
        # NB: this is the target image, not necessarily what is provisioned
        image_id: bfaefe6c-8eac-447b-8c58-4fd05c2e1161

a100:
    children:
        ms_a100:

ms_general:
    hosts:
        ms-general-00:
            ansible_host: 10.56.2.123
            instance_id: d54629f3-d96a-4187-9b86-752349b3f646
            networks: {"analytics-vxlan":{"fixed_ip_v4":"10.56.2.123","fixed_ip_v6":""}}
            node_fqdn: ms-general-00.in.nvs.bmrc.ox.ac.uk
        ms-general-01:
            ansible_host: 10.56.2.130
            instance_id: 89485c45-91ae-466c-8693-b55bfea64713
            networks: {"analytics-vxlan":{"fixed_ip_v4":"10.56.2.130","fixed_ip_v6":""}}
            node_fqdn: ms-general-01.in.nvs.bmrc.ox.ac.uk
        ms-general-02:
            ansible_host: 10.56.2.201
            instance_id: 1777d112-5379-4691-9042-c4785e4611f8
            networks: {"analytics-vxlan":{"fixed_ip_v4":"10.56.2.201","fixed_ip_v6":""}}
            node_fqdn: ms-general-02.in.nvs.bmrc.ox.ac.uk
        ms-general-03:
            ansible_host: 10.56.2.103
            instance_id: 16f4a995-4caf-4d7d-9636-3181e19dd00b
            networks: {"analytics-vxlan":{"fixed_ip_v4":"10.56.2.103","fixed_ip_v6":""}}
            node_fqdn: ms-general-03.in.nvs.bmrc.ox.ac.uk
        ms-general-04:
            ansible_host: 10.56.2.181
            instance_id: e7058503-528b-41ab-a5b0-93e19ea8eed1
            networks: {"analytics-vxlan":{"fixed_ip_v4":"10.56.2.181","fixed_ip_v6":""}}
            node_fqdn: ms-general-04.in.nvs.bmrc.ox.ac.uk
        ms-general-05:
            ansible_host: 10.56.1.251
            instance_id: a56de856-3820-43e6-ac17-4b1b93cc484a
            networks: {"analytics-vxlan":{"fixed_ip_v4":"10.56.1.251","fixed_ip_v6":""}}
            node_fqdn: ms-general-05.in.nvs.bmrc.ox.ac.uk
        ms-general-06:
            ansible_host: 10.56.1.149
            instance_id: c3dae76e-c628-4140-802d-8281a65d6e75
            networks: {"analytics-vxlan":{"fixed_ip_v4":"10.56.1.149","fixed_ip_v6":""}}
            node_fqdn: ms-general-06.in.nvs.bmrc.ox.ac.uk
        ms-general-07:
            ansible_host: 10.56.2.116
            instance_id: 720638aa-79f2-403c-991f-cbc8e159f857
            networks: {"analytics-vxlan":{"fixed_ip_v4":"10.56.2.116","fixed_ip_v6":""}}
            node_fqdn: ms-general-07.in.nvs.bmrc.ox.ac.uk
        ms-general-08:
            ansible_host: 10.56.1.8
            instance_id: b617e39a-1202-41e8-9607-e531b14f064b
            networks: {"analytics-vxlan":{"fixed_ip_v4":"10.56.1.8","fixed_ip_v6":""}}
            node_fqdn: ms-general-08.in.nvs.bmrc.ox.ac.uk
    vars:
        # NB: this is the target image, not necessarily what is provisioned
        image_id: bfaefe6c-8eac-447b-8c58-4fd05c2e1161

general:
    children:
        ms_general:

ms_general-100disk:
    hosts:
        ms-general-09:
            ansible_host: 10.56.2.28
            instance_id: de96f496-381c-4de4-8c05-649054cf9904
            networks: {"analytics-vxlan":{"fixed_ip_v4":"10.56.2.28","fixed_ip_v6":""}}
            node_fqdn: ms-general-09.in.nvs.bmrc.ox.ac.uk
        ms-general-10:
            ansible_host: 10.56.0.125
            instance_id: 02324113-1868-4663-abcf-5f08a652cb92
            networks: {"analytics-vxlan":{"fixed_ip_v4":"10.56.0.125","fixed_ip_v6":""}}
            node_fqdn: ms-general-10.in.nvs.bmrc.ox.ac.uk
        ms-general-11:
            ansible_host: 10.56.2.183
            instance_id: 2100b118-ce7e-4359-b689-30c6407ee28a
            networks: {"analytics-vxlan":{"fixed_ip_v4":"10.56.2.183","fixed_ip_v6":""}}
            node_fqdn: ms-general-11.in.nvs.bmrc.ox.ac.uk
        ms-general-12:
            ansible_host: 10.56.1.69
            instance_id: 8bb427ea-7c71-4034-86f4-289bc214c7e2
            networks: {"analytics-vxlan":{"fixed_ip_v4":"10.56.1.69","fixed_ip_v6":""}}
            node_fqdn: ms-general-12.in.nvs.bmrc.ox.ac.uk
        ms-general-13:
            ansible_host: 10.56.0.152
            instance_id: 78bb1a42-c00a-4e7b-8e32-818d1c17e61e
            networks: {"analytics-vxlan":{"fixed_ip_v4":"10.56.0.152","fixed_ip_v6":""}}
            node_fqdn: ms-general-13.in.nvs.bmrc.ox.ac.uk
        ms-general-14:
            ansible_host: 10.56.1.52
            instance_id: 26179481-f3db-46aa-bed5-ecfade6b9ed5
            networks: {"analytics-vxlan":{"fixed_ip_v4":"10.56.1.52","fixed_ip_v6":""}}
            node_fqdn: ms-general-14.in.nvs.bmrc.ox.ac.uk
        ms-general-15:
            ansible_host: 10.56.1.83
            instance_id: ed68870e-7257-4423-a7ee-61eed28e5c90
            networks: {"analytics-vxlan":{"fixed_ip_v4":"10.56.1.83","fixed_ip_v6":""}}
            node_fqdn: ms-general-15.in.nvs.bmrc.ox.ac.uk
    vars:
        # NB: this is the target image, not necessarily what is provisioned
        image_id: bfaefe6c-8eac-447b-8c58-4fd05c2e1161

general-100disk:
    children:
        ms_general-100disk:

ms_legacy:
    hosts:
        ms-legacy-00:
            ansible_host: 10.56.2.171
            instance_id: 6b8b5a71-5c71-42fd-8055-93aa4e312019
            networks: {"analytics-vxlan":{"fixed_ip_v4":"10.56.2.171","fixed_ip_v6":""}}
            node_fqdn: ms-legacy-00.in.nvs.bmrc.ox.ac.uk
        ms-legacy-01:
            ansible_host: 10.56.1.11
            instance_id: 9d8ca599-8075-4d54-883b-8f5d65849262
            networks: {"analytics-vxlan":{"fixed_ip_v4":"10.56.1.11","fixed_ip_v6":""}}
            node_fqdn: ms-legacy-01.in.nvs.bmrc.ox.ac.uk
    vars:
        # NB: this is the target image, not necessarily what is provisioned
        image_id: bfaefe6c-8eac-447b-8c58-4fd05c2e1161

legacy:
    children:
        ms_legacy:

ms_ood:
    hosts:
        ms-ood-00:
            ansible_host: 10.56.0.166
            instance_id: 7562b4e1-463f-443f-b6d8-6c87cead3be1
            networks: {"analytics-vxlan":{"fixed_ip_v4":"10.56.0.166","fixed_ip_v6":""}}
            node_fqdn: ms-ood-00.in.nvs.bmrc.ox.ac.uk
    vars:
        # NB: this is the target image, not necessarily what is provisioned
        image_id: bfaefe6c-8eac-447b-8c58-4fd05c2e1161

ood:
    children:
        ms_ood:

ms_v100:
    hosts:
        ms-v100-00:
            ansible_host: 10.56.1.17
            instance_id: ab83bf79-e4c8-45af-825b-3306d8a46d30
            networks: {"analytics-vxlan":{"fixed_ip_v4":"10.56.1.17","fixed_ip_v6":""}}
            node_fqdn: ms-v100-00.in.nvs.bmrc.ox.ac.uk
        ms-v100-01:
            ansible_host: 10.56.0.168
            instance_id: 479bfc15-14cc-4b0c-8ba1-ad94d1705da5
            networks: {"analytics-vxlan":{"fixed_ip_v4":"10.56.0.168","fixed_ip_v6":""}}
            node_fqdn: ms-v100-01.in.nvs.bmrc.ox.ac.uk
        ms-v100-02:
            ansible_host: 10.56.1.227
            instance_id: c1af9e06-0247-4c62-9908-d3ee8407a0df
            networks: {"analytics-vxlan":{"fixed_ip_v4":"10.56.1.227","fixed_ip_v6":""}}
            node_fqdn: ms-v100-02.in.nvs.bmrc.ox.ac.uk
    vars:
        # NB: this is the target image, not necessarily what is provisioned
        image_id: 67b2320a-7fc1-4b09-a0d8-148eff779ffa

v100:
    children:
        ms_v100:

ms_v100-full:
    hosts:
        ms-v100-03:
            ansible_host: 10.56.0.234
            instance_id: b8e18efa-9b4a-4106-b3ce-687c9217d558
            networks: {"analytics-vxlan":{"fixed_ip_v4":"10.56.0.234","fixed_ip_v6":""}}
            node_fqdn: ms-v100-03.in.nvs.bmrc.ox.ac.uk
    vars:
        # NB: this is the target image, not necessarily what is provisioned
        image_id: 67b2320a-7fc1-4b09-a0d8-148eff779ffa

v100-full:
    children:
        ms_v100-full:


compute:
    children:
        ms_a100:
        ms_general:
        ms_general-100disk:
        ms_legacy:
        ms_ood:
        ms_v100:
        ms_v100-full:

# --- additional nodes ---
additional:
    children:
