all:
    vars:
        openhpc_cluster_name: ms
        cluster_domain_suffix: in.nvs.bmrc.ox.ac.uk
        cluster_home_volume: false
        cluster_compute_groups: ["a100","general","legacy"]

control:
    hosts:
        ms-control:
            ansible_host: 10.56.2.244
            instance_id: c1015deb-6d93-4e4f-8ed8-49de53600de1
            networks: {"analytics-vxlan":{"fixed_ip_v4":"10.56.2.244","fixed_ip_v6":""}}
            node_fqdn: ms-control.in.nvs.bmrc.ox.ac.uk
    vars:
        appliances_state_dir: /var/lib/state # NB needs to be set on group not host otherwise it is ignored in packer build!

# --- login nodes ---
ms_interactive:
    hosts:
        ms-login-00:
            ansible_host: 10.56.2.112
            instance_id: 38b8f600-bd56-473c-8c53-19515d57ef92
            image_id: 57baae64-b01d-48bc-8066-c9e36354e958
            networks: {"analytics-vxlan":{"fixed_ip_v4":"10.56.2.112","fixed_ip_v6":""}}
            node_fqdn: ms-login-00.in.nvs.bmrc.ox.ac.uk
            node_fip:  10.167.2.160

login:
    children:
        ms_interactive:

# --- compute nodes ---
ms_a100:
    hosts:
        ms-a100-00:
            ansible_host: 10.56.0.35
            instance_id: 701a2f61-ca57-4746-bfd6-947b46769324
            networks: {"analytics-vxlan":{"fixed_ip_v4":"10.56.0.35","fixed_ip_v6":""}}
            node_fqdn: ms-a100-00.in.nvs.bmrc.ox.ac.uk
        ms-a100-01:
            ansible_host: 10.56.1.225
            instance_id: 60c95431-6ecd-41aa-a11c-45bfed9e5d47
            networks: {"analytics-vxlan":{"fixed_ip_v4":"10.56.1.225","fixed_ip_v6":""}}
            node_fqdn: ms-a100-01.in.nvs.bmrc.ox.ac.uk
        ms-a100-02:
            ansible_host: 10.56.1.73
            instance_id: 003ad207-24ab-4eb7-a7a9-e6a83e205096
            networks: {"analytics-vxlan":{"fixed_ip_v4":"10.56.1.73","fixed_ip_v6":""}}
            node_fqdn: ms-a100-02.in.nvs.bmrc.ox.ac.uk
        ms-a100-03:
            ansible_host: 10.56.0.57
            instance_id: 1a276cde-4528-42da-b8b4-2db5beb7640c
            networks: {"analytics-vxlan":{"fixed_ip_v4":"10.56.0.57","fixed_ip_v6":""}}
            node_fqdn: ms-a100-03.in.nvs.bmrc.ox.ac.uk
    vars:
        # NB: this is the target image, not necessarily what is provisioned
        image_id: 47a84b84-97bd-42a2-b72f-32b6dfe2d566

a100:
    children:
        ms_a100:

ms_general:
    hosts:
        ms-general-00:
            ansible_host: 10.56.2.123
            instance_id: d54629f3-d96a-4187-9b86-752349b3f646
            networks: {"analytics-vxlan":{"fixed_ip_v4":"10.56.2.123","fixed_ip_v6":""}}
            node_fqdn: ms-general-00.in.nvs.bmrc.ox.ac.uk
        ms-general-01:
            ansible_host: 10.56.2.130
            instance_id: 89485c45-91ae-466c-8693-b55bfea64713
            networks: {"analytics-vxlan":{"fixed_ip_v4":"10.56.2.130","fixed_ip_v6":""}}
            node_fqdn: ms-general-01.in.nvs.bmrc.ox.ac.uk
        ms-general-02:
            ansible_host: 10.56.2.201
            instance_id: 1777d112-5379-4691-9042-c4785e4611f8
            networks: {"analytics-vxlan":{"fixed_ip_v4":"10.56.2.201","fixed_ip_v6":""}}
            node_fqdn: ms-general-02.in.nvs.bmrc.ox.ac.uk
        ms-general-03:
            ansible_host: 10.56.2.103
            instance_id: 16f4a995-4caf-4d7d-9636-3181e19dd00b
            networks: {"analytics-vxlan":{"fixed_ip_v4":"10.56.2.103","fixed_ip_v6":""}}
            node_fqdn: ms-general-03.in.nvs.bmrc.ox.ac.uk
        ms-general-04:
            ansible_host: 10.56.2.181
            instance_id: e7058503-528b-41ab-a5b0-93e19ea8eed1
            networks: {"analytics-vxlan":{"fixed_ip_v4":"10.56.2.181","fixed_ip_v6":""}}
            node_fqdn: ms-general-04.in.nvs.bmrc.ox.ac.uk
        ms-general-05:
            ansible_host: 10.56.1.251
            instance_id: a56de856-3820-43e6-ac17-4b1b93cc484a
            networks: {"analytics-vxlan":{"fixed_ip_v4":"10.56.1.251","fixed_ip_v6":""}}
            node_fqdn: ms-general-05.in.nvs.bmrc.ox.ac.uk
        ms-general-06:
            ansible_host: 10.56.1.149
            instance_id: c3dae76e-c628-4140-802d-8281a65d6e75
            networks: {"analytics-vxlan":{"fixed_ip_v4":"10.56.1.149","fixed_ip_v6":""}}
            node_fqdn: ms-general-06.in.nvs.bmrc.ox.ac.uk
        ms-general-07:
            ansible_host: 10.56.2.116
            instance_id: 720638aa-79f2-403c-991f-cbc8e159f857
            networks: {"analytics-vxlan":{"fixed_ip_v4":"10.56.2.116","fixed_ip_v6":""}}
            node_fqdn: ms-general-07.in.nvs.bmrc.ox.ac.uk
        ms-general-08:
            ansible_host: 10.56.1.8
            instance_id: b617e39a-1202-41e8-9607-e531b14f064b
            networks: {"analytics-vxlan":{"fixed_ip_v4":"10.56.1.8","fixed_ip_v6":""}}
            node_fqdn: ms-general-08.in.nvs.bmrc.ox.ac.uk
    vars:
        # NB: this is the target image, not necessarily what is provisioned
        image_id: 57baae64-b01d-48bc-8066-c9e36354e958

general:
    children:
        ms_general:

ms_legacy:
    hosts:
        ms-legacy-00:
            ansible_host: 10.56.2.171
            instance_id: 6b8b5a71-5c71-42fd-8055-93aa4e312019
            networks: {"analytics-vxlan":{"fixed_ip_v4":"10.56.2.171","fixed_ip_v6":""}}
            node_fqdn: ms-legacy-00.in.nvs.bmrc.ox.ac.uk
        ms-legacy-01:
            ansible_host: 10.56.1.11
            instance_id: 9d8ca599-8075-4d54-883b-8f5d65849262
            networks: {"analytics-vxlan":{"fixed_ip_v4":"10.56.1.11","fixed_ip_v6":""}}
            node_fqdn: ms-legacy-01.in.nvs.bmrc.ox.ac.uk
    vars:
        # NB: this is the target image, not necessarily what is provisioned
        image_id: 57baae64-b01d-48bc-8066-c9e36354e958

legacy:
    children:
        ms_legacy:


compute:
    children:
        ms_a100:
        ms_general:
        ms_legacy:

# --- additional nodes ---
additional:
    children:
