all:
    vars:
        openhpc_cluster_name: ms
        cluster_domain_suffix: in.nvs.bmrc.ox.ac.uk
        cluster_home_volume: false
        cluster_compute_groups: ["a100","general","legacy"]

control:
    hosts:
        ms-control:
            ansible_host: 10.56.2.244
            instance_id: d6239cef-a77d-4a2b-a676-c0ee3963f434
            networks: {"analytics-vxlan":{"fixed_ip_v4":"10.56.2.244","fixed_ip_v6":""}}
            node_fqdn: ms-control.in.nvs.bmrc.ox.ac.uk
    vars:
        appliances_state_dir: /var/lib/state # NB needs to be set on group not host otherwise it is ignored in packer build!

# --- login nodes ---
ms_interactive:
    hosts:
        ms-login-00:
            ansible_host: 10.56.2.112
            instance_id: 38b8f600-bd56-473c-8c53-19515d57ef92
            image_id: c34bacd9-6172-4e56-aa5c-1a7085f72fb7
            networks: {"analytics-vxlan":{"fixed_ip_v4":"10.56.2.112","fixed_ip_v6":""}}
            node_fqdn: ms-login-00.in.nvs.bmrc.ox.ac.uk
            node_fip:  10.167.2.160

login:
    children:
        ms_interactive:

# --- compute nodes ---
ms_a100:
    hosts:
        ms-a100-00:
            ansible_host: 10.56.0.35
            instance_id: 701a2f61-ca57-4746-bfd6-947b46769324
            networks: {"analytics-vxlan":{"fixed_ip_v4":"10.56.0.35","fixed_ip_v6":""}}
            node_fqdn: ms-a100-00.in.nvs.bmrc.ox.ac.uk
    vars:
        # NB: this is the target image, not necessarily what is provisioned
        image_id: 9f5bf073-ce08-489b-a8b7-ccd14cf823a9

a100:
    children:
        ms_a100:

ms_general:
    hosts:
        ms-general-00:
            ansible_host: 10.56.2.123
            instance_id: d54629f3-d96a-4187-9b86-752349b3f646
            networks: {"analytics-vxlan":{"fixed_ip_v4":"10.56.2.123","fixed_ip_v6":""}}
            node_fqdn: ms-general-00.in.nvs.bmrc.ox.ac.uk
        ms-general-01:
            ansible_host: 10.56.2.130
            instance_id: 89485c45-91ae-466c-8693-b55bfea64713
            networks: {"analytics-vxlan":{"fixed_ip_v4":"10.56.2.130","fixed_ip_v6":""}}
            node_fqdn: ms-general-01.in.nvs.bmrc.ox.ac.uk
    vars:
        # NB: this is the target image, not necessarily what is provisioned
        image_id: c34bacd9-6172-4e56-aa5c-1a7085f72fb7

general:
    children:
        ms_general:

ms_legacy:
    hosts:
        ms-legacy-00:
            ansible_host: 10.56.2.171
            instance_id: 6b8b5a71-5c71-42fd-8055-93aa4e312019
            networks: {"analytics-vxlan":{"fixed_ip_v4":"10.56.2.171","fixed_ip_v6":""}}
            node_fqdn: ms-legacy-00.in.nvs.bmrc.ox.ac.uk
        ms-legacy-01:
            ansible_host: 10.56.1.11
            instance_id: 9d8ca599-8075-4d54-883b-8f5d65849262
            networks: {"analytics-vxlan":{"fixed_ip_v4":"10.56.1.11","fixed_ip_v6":""}}
            node_fqdn: ms-legacy-01.in.nvs.bmrc.ox.ac.uk
    vars:
        # NB: this is the target image, not necessarily what is provisioned
        image_id: c34bacd9-6172-4e56-aa5c-1a7085f72fb7

legacy:
    children:
        ms_legacy:


compute:
    children:
        ms_a100:
        ms_general:
        ms_legacy:

# --- additional nodes ---
additional:
    children:
