---
# Ansible managed
vault_demo_user_password: dDXxZuMIkM0Zqe6mQ4Vx
vault_elasticsearch_admin_password: e-0MK8bltZjXpamriMn,
vault_freeipa_admin_password: aCTeb23ehyw8u-GBkdDy
vault_freeipa_ds_password: tA,fEuSodkd3n6gNpGw-
vault_grafana_admin_password: 2G7yj5v:B1kHCdv2ov0H
vault_k3s_node_password: o.,afOFMk6zcY12hHrL3KiM44oB9Qc_RZRk-ffodPYPy3,lhr6TR5HaCeOt8SCST
vault_mysql_root_password: q:p4aQh6yhi4fEfXnurQ
vault_mysql_slurm_password: RT7tjyucC-Q,fqI549-5
vault_openhpc_mungekey:
    content: '3WxUWSh+RnLhQkex9wvR2vo8Rz9gXB4DFNGxCAgoyNx2n4B/jfBBg07X3w/i/oK3sjejr8h2H8kW

        k3kTe5Ib9E/vkJzrJOe/pnt/a9cJBJX+JcviZJ31fbeyNAw1fXT5q/52wzBbnV3LRsEY6jyrGRz5

        FuepWVZ/QqvFsGEouZ1S9yPjO63Q449xCpqRraimmAoE/C9c7l3WDUkjlIShaNqAoy/NgenJckDJ

        89UQEz+kvJrOlb3pTXF9qOTVoqMBZD6fCE15MDfWxjjTPX8lz/TsnCQ9klElQomKAjX7qVwrqwf+

        ONHVBNWvqojyCrR/tnC9K8YIFcCWqad4c+3Uj9lK8gOSI8uTQC7o1yWlUYsw1XRQJfbW8MIbWxTH

        9F/6ZHlEXBj3JtaD00LBxgT2vwzI6HqIjtKAjXQSO+79mZr9jNAu/YfnVukxJaABOaZibZQrPDda

        GCkYYYhhDTL8COwqPn9b2ZQsVAxpBgQrkBKbkrFmBnFE1CjTLu+omAl609tY6RdzCQYuGoo69PuY

        iol+CcPKdT2tJztvWDn4jFY52Bil4IbuaR2uUUz44cC3Jjlv1/E3H+HmzVvfyJnPboItL+fzcA/q

        MAq4nzcpqIOqMxu9POzv/fJmeWjiv7G/Eiet1bqpA0O/b4g9NI3zv9icRbgBkcRKME5rj2jwBkKZ

        QWkqc4Wfw69sCOZIUm91UxMc+8fkjFYnouCuaqL0H1jR6eLGhtAV5YhHPJDUl/w0lmr0PRsXf835

        TmF9LXKiO0ek/Ib8AxQmLWQnF/2756K1MFIu7LkQtGTdeoO7A1v54dC/V9S6m4CN9s3q+B+hd7LR

        xoZqyRF1jyT4ydTaHAkVlKcUElC9VgH69An0mRRcrkzS3fSYPFkH3hzkoLbX0qwTfe7UdJsy8nxE

        4l+2ch5YEzO2tHvpjxicNTImq3v6XkWRD2fb9VRXamqBwjPvQUVACQNk9ohVlfztEUwDie0a2K8C

        Amfawfo9AOH0GD4KHT4pbvFr3etOmLKUaMDC23giRMToj/RmVu9Os2FYKdfRbjrMba1Gs857bJPw

        LDAP8W5dA2LZrCPKg6HHS4wgP2ITURGWb4f30112cP3ygPFHBo46HsAYxwBML9Njwx06V+QxGkSq

        6b4OF9WSYuizqsKOH/AbdjizpV3oyqnGQnDdMqKVD2/6jp4ghvstO2Rw3Jl+1UJlmB6rV+Maehl1

        yiRcO1OkNqE+LsAuA0zdsnzlBB5ifG2qdNfrT/ZSpLCVT1G9uJMIEkzcPhivtDqi8fHrfSfTC0jZ

        wabIScp2nVZ7ORpfS317vzuVK5/g6/8zBEWeGPsqka3HKDCgs8oz7bVu5tUZPS4mRHs9LX8fNg=='
vault_pulp_admin_password: Se15HNVoPZALIewo9d60
