#!/bin/bash
# Source this file to quickly load required environment to run the ansible appliance

# We keep the ansible-vault password in the environment
# It could be read from vault in the future, if access to the vault server is possible from the deployment VM
if [ -z "$VAULT_BMRC_PASSWORD" ]; then
  read -p "Please enter ansible vault password:" -r -s VAULT_BMRC_PASSWORD
fi
export VAULT_BMRC_PASSWORD
export ANSIBLE_VAULT_IDENTITY_LIST=bmrc@$APPLIANCES_REPO_ROOT/dev/env-vault-client.py 
export ENV="bmrc-staging"
if [ -z "$OS_CLOUD" ] && [ -z "$OS_PROJECT_NAME" ]; then
  echo "Please export OS_CLOUD according to your ~/.config/openstack/clouds.yaml or source an openrc file"
fi
mydir="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"
source "$mydir/../venv/bin/activate"
source "$mydir/../environments/$ENV/activate"
