openhpc_nodegroups:
  - name: general # m2.xlarge.highmem_200disk
  - name: legacy  # m3.medium
  - name: a100
    gres_autodetect: nvidia # can't use nvml b/c disabling slurm package recompile for speed
    gres:
      - conf: "gpu:A100:3"

openhpc_partitions:
  # TODO: add maxtime, partition_params etc here
  # See https://github.com/stackhpc/ansible-role-openhpc/README.md
  - name: general
    default: 'YES'
  - name: legacy
    default: 'NO'
  - name: a100
    default: 'NO'

openhpc_config_extra:
  GresTypes:
    - gpu

