# Use fqhn without '.in' for external name - in NVS IpA:
openondemand_servername: "{{ hostvars[groups['openondemand'] | first].node_fqdn | split('.') | reject('eq', 'in') | join('.') }}"

# Install ondemand's DEX package:
install_ondemand_dex: true

# Use custom SSL cert - deployed by pre-hook
openondemand_ssl_cert: /etc/pki/tls/certs/ood.crt
openondemand_ssl_cert_key: /etc/pki/tls/private/ood.key

# WIP: Use DEX with LDAP adaptor pointing to NVS IpA:
# **NB**: This is a *text* block of yaml, not actual yaml!
dex_settings: |
  dex:
    ssl: false # doesn't appear to work with self-signed
    connectors:
      - type: ldap
        id: ldap
        name: LDAP
        config:
          host: ipa-a.nvs.bmrc.ox.ac.uk:636
          insecureSkipVerify: false
          bindDN: uid=svc-openondemand-dex,cn=users,cn=accounts,dc=nvs,dc=bmrc,dc=ox,dc=ac,dc=uk
          bindPW: "{{ vault_ondemand_oidc_ldap_bindpw }}" # site secret
          userSearch:
            baseDN: cn=users,cn=accounts,dc=nvs,dc=bmrc,dc=ox,dc=ac,dc=uk
            filter: "(objectClass=posixAccount)"
            username: uid
            idAttr: uid
            emailAttr: mail
            nameAttr: gecos
            preferredUsernameAttr: uid
          groupSearch:
            baseDN: cn=groups,cn=accounts,dc=nvs,dc=bmrc,dc=ox,dc=ac,dc=uk
            filter: "(objectClass=posixGroup)"
            userMatchers:
            - userAttr: DN
              groupAttr: member
            nameAttr: cn
#    oauth2:
#     skipApprovalScreen: true
#     enablePasswordDB: false
#    frontend:
#      dir: "/usr/share/ondemand-dex/web"
#      theme: ondemand

openondemand_auth: oidc

# WIP - Configure mapping from DEX OIDC to system users
# see https://osc.github.io/ood-documentation/latest/authentication/overview/map-user.html
## openondemand_mapping_users: [] # disable ansible/roles/openondemand default of a fixed list if users
## user_map_cmd: # null - disable (outdated) ansible/roles/openondemand default
# user_map_match: '.*' # TODO: maybe?

