# Use fqhn without '.in' for external name - in NVS IpA:
openondemand_servername: "{{ hostvars[groups['openondemand'] | first].node_fqdn | split('.') | reject('eq', 'in') | join('.') }}"

# Install ondemand's DEX package:
install_ondemand_dex: true

# Use custom SSL cert - deployed by pre-hook
openondemand_ssl_cert: /etc/pki/tls/certs/ood.crt
openondemand_ssl_cert_key: /etc/pki/tls/private/ood.key

# Use DEX with LDAP adaptor pointing to NVS IpA:
openondemand_auth: dex
# **NB**: This is a *text* block of yaml, not actual yaml!
dex_settings: |
  dex:
    connectors:
      - type: ldap
        id: ldap
        name: LDAP
        config:
          host: ipa-a.nvs.bmrc.ox.ac.uk:636
          insecureSkipVerify: false
          bindDN: uid=svc-openondemand-dex,cn=users,cn=accounts,dc=nvs,dc=bmrc,dc=ox,dc=ac,dc=uk
          bindPW: "{{ vault_ondemand_oidc_ldap_bindpw }}" # site secret
          userSearch:
            baseDN: cn=users,cn=accounts,dc=nvs,dc=bmrc,dc=ox,dc=ac,dc=uk
            filter: "(objectClass=posixAccount)"
            username: uid
            idAttr: uid
            emailAttr: mail
            nameAttr: gecos
            preferredUsernameAttr: uid
          groupSearch:
            baseDN: cn=groups,cn=accounts,dc=nvs,dc=bmrc,dc=ox,dc=ac,dc=uk
            filter: "(objectClass=posixGroup)"
            userMatchers:
            - userAttr: DN
              groupAttr: member
            nameAttr: cn

# NB: default `user_map_match: '.*'` is fine

# Override default jupyter config to use module from apps/
openondemand_apps_jupyter:
  jupyter:
    title: Jupyter Notebook
    description: Request a Jupyter Notebook server
    cluster: slurm
    form:
      - modules
      - extra_jupyter_args
      - bc_queue
      - bc_num_hours
      - num_cores
      - gres
      - gres_count
      - node
    attributes:
      num_cores:
        label: Number of cores
        value: 1
      modules:
        label: Module
        help: Choose the module to use
        widget: select
        options: # [label, module path]
          - ['JupyterNotebook/7.0.2-GCCcore-12.3.0', 'JupyterNotebook/7.0.2-GCCcore-12.3.0']
      gres:
        label: Resources
        help: Select GPU or other Slurm GRES resources
        required: true
        widget: select
        options: "{{ openondemand_gres_options }}"
      gres_count:
        label: Resource count
        help: Count of GPU or other Slurm GRES resources
        required: false
        widget: number_field
        value: 0
        min: 0
        step: 1
      node:
        label: Node name
        help: Select a particular node or leave empty to let Slurm pick the next available
        value: ""
      extra_jupyter_args: ""
      bc_queue:
        value: "{{ openondemand_jupyter_partition | default(none) }}"
        help: 'If GPUs are needed enter a100 and see GRES options'
    submit: |
      ---
      batch_connect:
        template: "basic"
      script:
        job_name: "ood-jupyter"
        native:
          - <%= "--nodes=1" %>
          - <%= "--ntasks=#{num_cores}" %>
          <% if node != '' %>
          - <%= "--nodelist=#{node}" %>
          <% end %>
          <% if gres != 'none' %>
          - <%= "--gres=#{gres}:#{gres_count}" %>
          <% end %>

openondemand_apps_rstudio_module_options:
 - ['RStudio-Server/2023.09.1+494-foss-2023a-Java-11-R-4.3.2', 'RStudio-Server/2023.09.1+494-foss-2023a-Java-11-R-4.3.2']

openondemand_desktop_partition: ood
openondemand_jupyter_partition: ood
openondemand_rstudio_partition: ood
