all:
    vars:
        openhpc_cluster_name: ff28d9
        cluster_domain_suffix: in.nvs.bmrc.ox.ac.uk
        cluster_home_volume: true
        cluster_compute_groups: ["general"]

control:
    hosts:
        control:
            ansible_host: 10.56.1.132
            instance_id: a5692cfd-77b5-4825-904e-a606f3ba1d85
            networks: {"analytics-vxlan":{"fixed_ip_v4":"10.56.1.132","fixed_ip_v6":""}}
            node_fqdn: control.ff28d9.in.nvs.bmrc.ox.ac.uk
    vars:
        appliances_state_dir: /var/lib/state # NB needs to be set on group not host otherwise it is ignored in packer build!

# --- login nodes ---
ff28d9_interactive:
    hosts:
        login-0:
            ansible_host: 10.56.0.144
            instance_id: 018bc31e-27b4-44b8-971a-d5d4b61e2fb6
            image_id: c351ccaf-ae32-406b-b7c6-4e03220d5510
            networks: {"analytics-vxlan":{"fixed_ip_v4":"10.56.0.144","fixed_ip_v6":""}}
            node_fqdn: login-0.ff28d9.in.nvs.bmrc.ox.ac.uk

login:
    children:
        ff28d9_interactive:

# --- compute nodes ---
ff28d9_general:
    hosts:
        compute-0:
            ansible_host: 10.56.1.229
            instance_id: 6b6a0ca1-4196-4203-86e9-8469d3817b9c
            networks: {"analytics-vxlan":{"fixed_ip_v4":"10.56.1.229","fixed_ip_v6":""}}
            node_fqdn: compute-0.ff28d9.in.nvs.bmrc.ox.ac.uk
        compute-1:
            ansible_host: 10.56.2.206
            instance_id: a5858b7e-0d15-4e19-b36e-9924ce53dffa
            networks: {"analytics-vxlan":{"fixed_ip_v4":"10.56.2.206","fixed_ip_v6":""}}
            node_fqdn: compute-1.ff28d9.in.nvs.bmrc.ox.ac.uk
    vars:
        # NB: this is the target image, not necessarily what is provisioned
        image_id: c351ccaf-ae32-406b-b7c6-4e03220d5510

general:
    children:
        ff28d9_general:


compute:
    children:
        ff28d9_general:

# --- additional nodes ---
additional:
    children:
