---
# Ansible managed
vault_alertmanager_admin_password: Nt:EvkuO0Fk-55Q_7kCm
vault_demo_user_password: Qx.3BY1Pbk4OpoTVw3-c
vault_elasticsearch_admin_password: hogHalhIwl,NnVKvq,QF
vault_freeipa_ds_password: -wyRhTHe_q2IZVNIGTU0
vault_grafana_admin_password: _saHeVkkcaoKQtJTMpAU
vault_k3s_node_password: :newOebr0-y8OoWj,3V2Q2udXS2zP28WM2Z.lVDQwVLWJecLFmW6rN42RuB-e0KT
vault_mysql_root_password: 8WH.HfWdC6CugfxhbCz1
vault_mysql_slurm_password: ozKhftLDQW,whlZl1IoH
vault_openhpc_mungekey:
    content: '0ky+UfXZoUqLjpN8JL9fcMPmC1OWZeHyezodVL66bFRI2n5KAKOUobfn76G4IOO1WAHY3OHGdzQ+

        01BIjPB/8Ct1KiEzrG/lEK9G2F+LD0eGjhtKlDUSEvanYmBMvEZjSbC13M88b6E7+6jWeqY/8xN3

        orj59ey/Hw8pqgzgjiWAfQJSu9QtE4DcZNQ8kpD5h1yJe3pBBI0sRopkl1q1zL+mxlJynkfT3Kzj

        DPKu555OufR26JkljZcPz9ZIPx/t5xD+fclZs/b3UHHwoTXvDbooqSj4tRGMs9K5ZXxHIGlf4Zpx

        UoYVcf2dRTnLrCcKAAE1vR00I9pZbXmJ3AQT+MSkT4zLaOEvK5tCyPcsjsTfMInEQwiE+ZnV4JgD

        RAJuPFG0Mli9zbfGARHuhsjinP+aA12Jjmauz9sDspnnc13jYx0Tc4Zg7vZI+EIxsJNtGc97CW7q

        lZiaxmWJeUmDzim5vOA2FN52eI07eTjTiUGv4VNb+z7FIOb7X60pKaKhmDjSY+0SOawPbFBuhT5B

        ru74BXQVgu72b8eRXPYC+ByKR209cD74bLeY6dUF+hKiYF7Bct6U7UBu46IrhK6DvEnJ5V7SrSDY

        cNnNkLuW7Ey440JskXNI3upREDK2cdXeOHOQA9qrZqNdv8FmYH3ewXVN4yL8Fb4xD9IKbyFR7R3j

        lxppvGhltaV6nXpTcfWocqybqwFs80tsugAKuCiHmXKU0AH8b3JWxHEo8GP3FmTHSGoTqrLwl5Sx

        apYogCDELVAqESlG1IWD9495PMQaAsjzHckpqud+siH+TrswRnTwvEwsm+RFOUhP0ErOhoY+GK0F

        sjQrn/xwc1SogxHT77P0vs2swUvLok3qVzOGr3CEJIj4I1eVi+QY6uE44y8vU+FZla657qpEWsUH

        PCExja9LdpZ3zG4vgSyHVhlYzaMHk2SOfTIgcY1wgrlLxAzO6GthY5n4B7ChfE/vcNpFsTWrKwAE

        sJMeJA1zIsDHcEih0mGfKOJfCb/WD6Q1jkRE0ycDxos9Fu1tqulX3gF4kwHxlSHCLufACDZCytdw

        IBJHRapydIivsLfGv/tbKFxEqruTAsGWPR7xOiBNolngJWwYB5/o7OvobaO8iPWl4N5Yi4qtx8Z0

        uiMTLkVkA625zvFc5qv67v4aLhX+74w+rT/yVhhW4HVab8H5IQs5ou8uBVTAm645SOwfzeLfr493

        5iZvVojGXg+b/ADR8nsEw7p5S3gfdwY1oe5SnDBnwqxfV9TaR3DB+7nN8Cyn8xFRA8d8SWs4+XtC

        wMN6P/y/fQwERwodI4Lhq/nhiiRK2ejcCUjg44rlR2hf/vxhVbe1HNcVzOEXWewPs8hCrFNdOQ=='
vault_pulp_admin_password: L0ruynb5HrFy4lMx9jjU
