---

# This file governs the main CI workflow.
# It's the only workflow triggered on push and pull requests,
# it manages the CI workflow as follows:
# 1. Lint the code aborting the workflow if there are linting errors.
# 2. Determine which files have changed and set job outputs accordingly.
# 3. Conditionally run the other workflows based on the changed files:
#    * stackhpc.yml
#    * extra.yml
#    * scan.yml

name: Test on push and pull request

permissions: {}

'on':
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    permissions:
      contents: read
      # To write Super-linter status checks
      statuses: write
      pull-requests: write
      issues: write
    uses: ./.github/workflows/lint.yml

